
export const  CREATE_APPOINTMENT                = 'CREATE_APPOINTMENT';
export const  CREATE_APPOINTMENT_PENDING        =  CREATE_APPOINTMENT+'_PENDING';
export const  CREATE_APPOINTMENT_REJECTED       =  CREATE_APPOINTMENT+'_REJECTED';
export const  CREATE_APPOINTMENT_FULFILLED      = CREATE_APPOINTMENT + '_FULFILLED';



export const  DELETE_APPOINTMENT                = 'DELETE_APPOINTMENT';
export const  DELETE_APPOINTMENT_PENDING        = 'DELETE_APPOINTMENT_PENDING';
export const  DELETE_APPOINTMENT_REJECTED       = 'DELETE_APPOINTMENT_REJECTED';
export const  DELETE_APPOINTMENT_FULFILLED      = 'DELETE_APPOINTMENT_FULFILLED';


export const  UPDATE_APPOINTMENT                = 'UPDATE_APPOINTMENT';
export const  UPDATE_APPOINTMENT_PENDING        = 'UPDATE_APPOINTMENT_PENDING';
export const  UPDATE_APPOINTMENT_REJECTED      = 'UPDATE_APPOINTMENT_REJECTED';
export const  UPDATE_APPOINTMENT_FULFILLED    = 'UPDATE_APPOINTMENT_FULFILLED';



export const  GET_MY_APPOINTMENTS               = 'GET_MY_APPOINTMENTS';
export const  GET_MY_APPOINTMENTS_FULFILLED     = 'GET_MY_APPOINTMENTS_FULFILLED';
export const  GET_MY_APPOINTMENTS_PENDING       = 'GET_MY_APPOINTMENTS_PENDING';
export const  GET_MY_APPOINTMENTS_REJECTED      = 'GET_MY_APPOINTMENTS_REJECTED';

export const SET_APPOINTMENT_START_END_DATE  ="SET_APPOINTMENT_START_END_DATE";


export const UPDATE_FIELD_BY_VALUE = "UPDATE_FIELD_BY_VALUE";

export const TEMP_NAME ="temp";

export const  TEMP_NAME_PENDING        =  "temp_PENDING";
export const  TEMP_NAME_REJECTED        =  "temp_REJECTED";
export const  TEMP_NAME_FULFILLED      =  "temp_FULFILLED";

