export const UPDATE_LOGIN_FIELD = "UPDATE_LOGIN_FIELD";

export const LOGIN_REJECTED = "LOGIN_REJECTED";
export const LOGIN_PENDING = "LOGIN_PENDING";
export const LOGIN_FULFILLED = "LOGIN_FULFILLED";
export const LOGIN = 'LOGIN';
