export const UPDATE_FIRST_NAME = ""
export const UPDATE_LAST_NAME = ""
export const UPDATE_EMAIL = ""
export const UPDATE_PASSWORD = ""
export const UPDATE_CONFIRM_PASSWORD = ""
export const UPDATE_USERNAME = ""
export const UPDATE_ROLE = "update_role"

export const  REGISTER_USER = 'register_user'



export const UPDATE_FIELD = 'update_field'


export const CREATE_USER = 'CREATE_USER'

export const CREATE_USER_PENDING = 'CREATE_USER_PENDING'
export const CREATE_USER_FULFILLED= 'CREATE_USER_FULFILLED'
export const CREATE_USER_REJECTED = 'CREATE_USER_REJECTED'


export const  GET_PROFILE       = 'GET_PROFILE'


export const  GET_PROFILE_PENDING  = 'GET_PROFILE_PENDING'

export const  GET_PROFILE_REJECTED = 'GET_PROFILE_REJECTED'


export const  GET_PROFILE_FULFILLED = 'GET_PROFILE_FULFILLED'

export const SET_UPDATE_MODE ="SET_UPDATE_MODE"


export const  UPDATE_USER       = 'UPDATE_USER'


export const  UPDATE_USER_PENDING  = 'UPDATE_USER_PENDING'

export const  UPDATE_USER_REJECTED = 'UPDATE_USER_REJECTED'


export const  UPDATE_USER_FULFILLED = 'UPDATE_USER_FULFILLED'

export const RESET_UPDATE_SUCCESS = "RESET_UPDATE_SUCCESS"
export const RESET_SELECTED_ROLE = "RESET_SELECTED_ROLE"

export const RESET_ADMIN_SCREEN = "RESET_ADMIN_SCREEN"
