export const UPDATE_FIRST_NAME = ""
export const UPDATE_LAST_NAME = ""
export const UPDATE_EMAIL = ""
export const UPDATE_PASSWORD = ""
export const UPDATE_CONFIRM_PASSWORD = ""
export const UPDATE_USERNAME = ""
